[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "93b369ecb137242385030af6a1b541514671cc83"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[OpenMPI.download]]
    sha256 = "f71d35e8e83019a2bfe4f524ffa6035247ba846b27a6cab460ccfb9f7b6b7108"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "186e334cd8381a0ebe792e1279b11382facdbb73"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "d967f8845e4603c2cfa202a80a8dec047f32c238682cf9c16809f2d7d65ab6af"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "aarch64"
git-tree-sha1 = "fbb5c43fa70e4e1f9a6029198a523ee4503820b1"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "4deaf101fd8e8dd854d090120cb601d539eb58b0e04f1ef1ec96a49712d2077e"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "powerpc64le"
git-tree-sha1 = "81401eb5251a59fd3f5b7c5468ce8ef5d0693040"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "9c722952a01f63b9a323eba41d38f246ecc256ae65702116d39a05ce507980e9"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "riscv64"
git-tree-sha1 = "856fd10e3a233a71a9bee9fe32c6803f0d85de7b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "4958d04cad8bc7aa1b9a6f49f4f0ab3faf3daae6b10a98f4fee05f4542b79069"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "3a80d5ce814781430217813fbf2f5c2196c87882"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[OpenMPI.download]]
    sha256 = "2590b8cc0bb61f61460cd317c4d155996eb06325fb67c29f6f5796cd569c6d0f"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "490e23c8b9e3ec722c3302f03b2027c8cc2adad1"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "0a1248d6cd46758b9031a76fe00abf0b191d73db1a1909456c84dc009a124c9a"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[OpenMPI]]
arch = "x86_64"
git-tree-sha1 = "9d59a8fcbf915c9e31fd3a78ce0430fc9afc2c69"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[OpenMPI.download]]
    sha256 = "67bd9f5704a74d572b0b543b3cc394e129fd7cda3e59decdfcec4ef9ce3d981f"
    url = "https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/releases/download/OpenMPI-v5.0.12+0/OpenMPI.v5.0.12.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
